title: ozkar's blog
url: http://ozkar.org/ #for prod
#url: http://localhost:4000/ #for dev
paginate_path: "blog/page/:num/"
permalink: blog/:title/
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about

social:
   email: ozkar@ozkar.org
   github: ozkar99
   linkedin: oscar-moreno-garza-134b5863

google_analytics: 
