title: ozkar99 blog
description: random thoughts

url: http://ozkar99.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: ozkar99
   facebook: ozkar99
   email:
   twitter:

google_analytics: 
