title: ozkar's blog
description: random thoughts about programming

url: http://ozkar.org/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about

social:
   github: ozkar99
   facebook: ozkar99
   email: ozkar@ozkar.org
   twitter:

google_analytics: 
