title: ozkar's blog
url: http://ozkar.org/
paginate_path: "blog/page:num/"
permalink: blog/:title/
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about

social:
   github: ozkar99
   facebook:
   email: ozkar@ozkar.org
   twitter:

google_analytics: 
