title: ozkar's blog
url: https://ozkar.org

plugins:
  - jekyll-paginate
paginate_path: "blog/page/:num/"
permalink: blog/:title/
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about

social:
  facebook: ozkar99
  email: ozkar@ozkar.org
  github: ozkar99
  gitlab: ozkar99
  linkedin: oscar-moreno-garza-134b5863

google_analytics: 
